flowchart LR
  Dev[Developpeur / VS Code]
  Git[GitHub]
  Vercel[Vercel - Application Next.js]
  SupabaseAuth[Supabase Auth]
  SupabaseDB[(Supabase PostgreSQL)]
  User[Utilisateur web]
  Email[SMTP Gmail / Nodemailer]

  Dev --> Git
  Git --> Vercel
  User --> Vercel
  Vercel --> SupabaseAuth
  Vercel --> SupabaseDB
  Vercel --> Email
